# <center> Numpy Tutorial

## Import Numpy

In [4]:
#!pip install numpy 
import numpy as np

## Check Python and Numpy Version

In [2]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.9.5
Numpy version: 1.20.3


# Numpy Data Types

## A list of Numpy Data Types

In [5]:
import pandas as pd
dtypes = pd.DataFrame({'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']})
dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## Create an array with a specified data type

In [6]:
arr = np.array([1,2,3.2],dtype='f2')
print("The datatype of ",arr," is ",arr.dtype)

The datatype of  [1.  2.  3.2]  is  float16


In [9]:
arr = np.array([1+2j, 3-4j,"Manoj"])
print("The datatype of ",arr," is ",type(arr))

The datatype of  ['(1+2j)' '(3-4j)' 'Manoj']  is  <class 'numpy.ndarray'>


In [6]:
arr = np.array([0, 1, 1], dtype=bool)
print("The datatype of ",arr," is ",arr.dtype)

The datatype of  [False  True  True]  is  bool


## String data type

Set the max length of the string using S + some number, such as 'S3' any string longer than the max length will be truncated

In [7]:
s = np.array(['abc', 'defg'], dtype='S4')
print("The datatype of ",s," is ",s.dtype)

The datatype of  [b'abc' b'defg']  is  |S4


# Create Arrays

## Create an Array From A Python Array

In [8]:
arr = np.array(range(1,10,2))
print(arr)

[1 3 5 7 9]


In [9]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Create an Array in a Specified Data Type

In [10]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


## Create An Aray Of Evenly Spaced Values Within A Specified Interval

In [11]:
arr = np.arange(0, 20, 2)  # np.arange(start, stop, step)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


## Create An Array Of Evenly Spaced Numbers In A Specified Interval

In [11]:
#np.linspace(start, stop, num_of_elements, endpoint=True, retstep=True) 
arr = np.linspace(0, 10, 4,retstep=True)
print(arr)

(array([ 0.        ,  3.33333333,  6.66666667, 10.        ]), 3.3333333333333335)


In [13]:
# exclude endpoint and return step size
arr, step = np.linspace(0, 10, 5, endpoint=False, retstep=True)
print("array: ",arr)
print("step :",step)

array:  [0. 2. 4. 6. 8.]
step : 2.0


## Create An Array Of Random Values In A Given Shape

In [14]:
arr = np.random.rand(2, 3)
print(arr)

[[0.66412799 0.57515248 0.52220475]
 [0.33347117 0.15226307 0.39663309]]


## Create an Array of Zeros in a Given Shape 

In [15]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


## Create An Array Of Zeros With The Same Shape And Data Type As A Given Array

In [16]:
zeros = np.zeros_like(np.array([[1,2,3,4],[3,4,5,6]]))
print(zeros)

[[0 0 0 0]
 [0 0 0 0]]


## Create An Array Of Ones In A Given Shape 

In [17]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


## Create an array of ones with the same shape and data type as a given array

In [18]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


## Create an array of arbitrary values in a given shape 

In [19]:
empty1 = np.empty((2,3))
print(empty1)

[[1. 1. 1.]
 [1. 1. 1.]]


## Create an array of arbitrary values with the same shape and data type as a given array

In [20]:
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


## Create an array of constant values in a given shape  

In [21]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


## Create an array of constant values with the same shape and data type as a given array

In [22]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]]


## Create an array by repetition

Repeat each element of an array by a specified number of times

In [3]:
# np.repeat(iterable, reps, axis=None)
import numpy as np
arr = np.array([[0, 1, 2],[3,4,5]])
print(arr)
print(np.repeat(arr, [1,2],axis=0))    # or np.repeat(range(3), 3)
type(arr)

np.repeat(range(3), [1,5,3])

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [3 4 5]]


array([0, 1, 1, 1, 1, 1, 2, 2, 2])

Repeat along a specified axis with specified number of repetitions.

In [24]:
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,2], axis=1))

[[1 2 2]
 [3 4 4]]


## Repeat an array by a specified number of times

In [7]:
arr = [0, 1, 2]
print(np.tile(arr,(2,3)))

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


In [8]:
# repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


## create an identity matrix with a given diagonal size

In [9]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
identity_matrix = np.identity(2)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


## Create an identity matrix with a diagonal offset

In [12]:
identity_matrix = np.eye(5, k=-1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [30]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Extract the diagonal array / create a diagonal array

In [13]:
arr = np.random.rand(4,4)
print(arr)

[[0.20296491 0.48453347 0.41064273 0.45295622]
 [0.57608403 0.55502894 0.22764523 0.04831637]
 [0.22489154 0.88230937 0.06543156 0.56067435]
 [0.1959422  0.39817831 0.26052539 0.59553843]]


In [14]:
print(np.diag(arr)) # extract the diagonal

[0.20296491 0.55502894 0.06543156 0.59553843]


In [15]:
arr = np.diag([1,2,3])    # create a matrix with a specified diagonal array
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Inspect Arrays

In [16]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

## Inspect general information of an array

In [19]:
np.info(arr)

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2336aca4610
byteorder:  little
byteswap:  False
type: int64


## Inspect the data type of an array

In [20]:
print(arr.dtype)

int64


## inspect the dimension of an array

In [21]:
nrow, ncol =arr.shape
print(nrow, ncol)

2 3


## Inspect length of an array

In [22]:
print(len(arr))

2


## Inspect the number of dimensions of an array

In [39]:
print(arr.ndim)

2


## Inspect the number of elements in an array

In [40]:
print(arr.size)

6


## Inspect the number of bytes of each element in an array

In [24]:
print(arr.itemsize)

8


## Inspect the memory size of an array (in byte)

In [42]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


# Sampling Methods

### Set seed

In [25]:
np.random.seed(123)

### Generate a random sample from interval [0, 1) in a given shape

In [27]:
print(np.random.rand())   # generate a random scalar   

0.28613933495037946


In [45]:
print(np.random.rand(1,3))        # generate a 1-D array   

[[0.28613933 0.22685145 0.55131477]]


In [46]:
print(np.random.rand(3,3))          # generate a 2-D array

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


## Generate a sample from the standard normal distribution (mean = 0, var = 1)

In [29]:
print(np.random.randn(3,3))

[[-0.09470897  1.49138963 -0.638902  ]
 [-0.44398196 -0.43435128  2.20593008]
 [ 2.18678609  1.0040539   0.3861864 ]]


## Generate an array of random integers in a given interval [low, high)

In [31]:
# np.ranodm.randint(low, high, size)
print(np.random.randint(1, 10, 30))

[9 2 3 2 2 4 6 1 9 2 7 4 4 6 8 3 4 4 4 9 7 8 7 4 7 7 7 2 4 5]


## Generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [32]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(5))
print(np.random.random(5))
print(np.random.ranf(5))
print(np.random.sample(5))

[0.72341636 0.01612921 0.59443188 0.55678519 0.15895964]
[0.15307052 0.69552953 0.31876643 0.6919703  0.55438325]
[0.38895057 0.92513249 0.84167    0.35739757 0.04359146]
[0.30476807 0.39818568 0.70495883 0.99535848 0.35591487]


## Sampling Discrete Distribution

Generate a random sample from a given Discrete Distribution

In [50]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(4), 10, replace=True, p=[0.1, 0.4, 0.4,0.1]))

[0 2 2 2 0 2 2 1 1 2]


In [33]:
print(np.random.choice(['a','b','c'], 10))

['a' 'a' 'a' 'a' 'a' 'b' 'a' 'a' 'a' 'c']


In [34]:
print(np.random.choice([1,2,3], 10))

[3 2 2 1 3 3 2 3 3 1]


## Sampling from Various Distributions

In [39]:
x=np.random.normal(loc=100,scale=10,size=10)
x

array([ 87.80737275,  96.30498038, 101.23482752,  94.66904131,
       105.67914291,  96.51387393,  93.14968625, 125.54368342,
        95.51849254,  90.4760479 ])

In [54]:
np.random.binomial(n=10,p=0.3,size=10)

array([1, 2, 4, 4, 3, 5, 3, 2, 2, 2])

In [55]:
np.random.poisson(lam=3,size=5)
np.random.poisson(3,5)

array([2, 2, 5, 4, 2])

In [56]:
np.random.exponential(scale=10,size=10)

array([10.9324407 , 21.87978588, 11.91752011,  5.80404161,  5.76634969,
       14.48578764,  8.33886203,  0.8872648 ,  8.7388061 , 16.86554961])

In [57]:
np.random.uniform(low=10,high=20,size=5)

array([13.37066383, 19.2757658 , 17.50717   , 15.74063825, 17.51643989])

In [58]:
np.random.laplace(loc=0,scale=1,size=5)

array([-1.84327644,  1.26861142,  1.03004254,  1.71337344, -1.35765872])

## Sampling from some standard distributions

In [59]:
np.random.standard_normal(10)

array([ 0.30741813, -1.41188888, -1.87686866, -1.01965507,  0.1679423 ,
        0.55385617, -0.53067456,  1.37725748, -0.14317597,  0.020316  ])

In [60]:
np.mean(np.random.standard_exponential(100))

0.9964807268694197

In [61]:
np.random.standard_t(2,10)

array([-0.17429494, -0.05772449,  0.8164722 , -0.20400207,  0.52191113,
       -0.05171771, -0.16783754,  4.63631236,  1.49234629, -1.72638199])

In [62]:
np.random.standard_gamma(2,10)

array([3.34893511, 1.85460333, 2.73256722, 1.45859021, 1.66691251,
       0.28106586, 0.50818487, 1.99015223, 2.47878993, 1.05162734])

## Shuffle an array in place

In [41]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
np.random.shuffle(arr)
print(arr)

[9 6 0 1 5 3 7 8 4 2]


## Generate a permutation of an array

In [44]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('A permutation of the array: ', np.random.permutation(arr))
print('The initial array: ', arr)

A permutation of the array:  [8 9 2 5 3 4 6 7 0 1]
The initial array:  [0 1 2 3 4 5 6 7 8 9]


# Math Functions

In [45]:
arr = np.random.randint(1,9,size=(3,3))
arr

array([[5, 6, 1],
       [8, 2, 3],
       [3, 3, 8]])

### element-wise operations

In [67]:
print(arr + 10) # addition, subtraction, multiplication and division
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[15 12 12]
 [16 18 13]
 [18 15 13]]
[[-5 -8 -8]
 [-4 -2 -7]
 [-2 -5 -7]]
[[50 20 20]
 [60 80 30]
 [80 50 30]]
[[0.5 0.2 0.2]
 [0.6 0.8 0.3]
 [0.8 0.5 0.3]]


In [51]:
arr1 = np.array([1,2,3])
arr2=np.array([8,9,10])
arr3=np.add(arr1,arr2)
arr3

array([ 9, 11, 13])

In [53]:
np.subtract(arr1, [8,9,10], out=arr3)
print(arr3)

[-7 -7 -7]


In [60]:
np.multiply([4,5,3], [1,2,3])
# print("Multiplication:",arr3)
np.divide([4,6,9],[1,2,3])

array([4., 3., 3.])

## Element-wise Exponentiation

In [61]:
print(np.exp(arr1))

[ 2.71828183  7.3890561  20.08553692]


## Element-wise Logorithm

In [62]:
# natural log
print(np.log(arr))      

[[1.60943791 1.79175947 0.        ]
 [2.07944154 0.69314718 1.09861229]
 [1.09861229 1.09861229 2.07944154]]


In [63]:
# base 2
print(np.log2(arr))     

[[2.32192809 2.5849625  0.        ]
 [3.         1.         1.5849625 ]
 [1.5849625  1.5849625  3.        ]]


In [64]:
# base 10
print(np.log10(arr))    

[[0.69897    0.77815125 0.        ]
 [0.90308999 0.30103    0.47712125]
 [0.47712125 0.47712125 0.90308999]]


## Element-wise square root

In [75]:
print(np.sqrt([1,4,9]))

[1. 2. 3.]


## Element-wise sine and cosine

In [76]:
print(np.sin(arr))

[[-0.95892427  0.90929743  0.90929743]
 [-0.2794155   0.98935825  0.14112001]
 [ 0.98935825 -0.95892427  0.14112001]]


In [77]:
print(np.cos(arr))

[[ 0.28366219 -0.41614684 -0.41614684]
 [ 0.96017029 -0.14550003 -0.9899925 ]
 [-0.14550003  0.28366219 -0.9899925 ]]


## Sum along a specified axis

In [65]:
# Sum along the row
print(arr)
print(np.sum(arr, axis=0))

[[5 6 1]
 [8 2 3]
 [3 3 8]]
[16 11 12]


In [66]:
# sum along the column
print(np.sum(arr, axis=1))    

[12 13 14]


## Compute the min and max along a specified axis

In [67]:
# calculate min along the row
print(np.min(arr, axis=0))

[3 2 1]


In [68]:
# calculate max along the column
print(np.max(arr, axis=1))    

[6 8 8]


In [70]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

8
1


## Indices of the min and max along a specified axis

In [72]:
# along the row
print(arr)
print(np.argmin(arr, axis=0)) # Index of Column Minimum
print(np.argmax(arr, axis=0)) # Index of Row Minimum

[[5 6 1]
 [8 2 3]
 [3 3 8]]
[2 1 0]
[1 0 2]


In [73]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[2 1 0]
[1 0 2]


In [74]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

2
3


## Element-wise min and max of two arrays

In [75]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


## Split fractional and integral parts of a floating-point array

In [76]:
arr1 = np.random.rand(5) * 100
re, intg = np.modf(arr1)
print("Original :", arr1)
print('integral: ', intg)
print('fractional: ', re)

Original : [ 2.93197229 63.59003594  3.21979349 74.47806551 47.29130022]
integral:  [ 2. 63.  3. 74. 47.]
fractional:  [0.93197229 0.59003594 0.21979349 0.47806551 0.29130022]


## Compute the mean

In [79]:
print(arr)
# compute the overall mean
print(np.mean(arr))

[[5 6 1]
 [8 2 3]
 [3 3 8]]
4.333333333333333


In [89]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[6.33333333 5.         2.66666667]


In [90]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[3.         5.66666667 5.33333333]


## Median

In [91]:
# compute the overall median
print(np.median(arr))

5.0


In [92]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[6. 5. 3.]


In [93]:
# compute the median along the column
print(np.median(arr, axis=1))

[2. 6. 5.]


## Compute the percentile

In [80]:
arr1 = np.random.rand(100)
# print(arr1)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [50, 60, 90]))

[0.45263823 0.5550912  0.93079019]


## Compute the standard deviation & variance

In [95]:
# compute the overall standard deviation
print(np.std(arr))

2.211083193570267


In [96]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[1.24721913 2.44948974 0.47140452]


In [97]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[1.41421356 2.05480467 2.05480467]


In [98]:
# compute the overall variance
print(np.var(arr))

4.888888888888889


In [99]:
# compute the variance along the row
print(np.var(arr, axis=0))

[1.55555556 6.         0.22222222]


In [100]:
# compute the variance along the column
print(np.var(arr, axis=1))

[2.         4.22222222 4.22222222]


## Compute the covariance & correlation

In [81]:
arr = np.random.rand(5,3)
print(arr)

[[0.5964869  0.01639248 0.72118437]
 [0.00773751 0.08482228 0.22549841]
 [0.87512453 0.36357632 0.53995994]
 [0.56810321 0.22546336 0.57214677]
 [0.6609518  0.29824539 0.41862686]]


In [82]:
print(np.cov(arr))

[[ 0.1414651   0.01359753  0.06321097  0.07393456  0.04417176]
 [ 0.01359753  0.01219194 -0.01460089  0.00387305 -0.01063221]
 [ 0.06321097 -0.01460089  0.06752134  0.03917847  0.04799898]
 [ 0.07393456  0.00387305  0.03917847  0.0396013   0.02750535]
 [ 0.04417176 -0.01063221  0.04799898  0.02750535  0.03412817]]


In [84]:
print(np.corrcoef(arr))

[[ 1.          0.32741532  0.64676614  0.98779789  0.63571655]
 [ 0.32741532  1.         -0.50888826  0.1762633  -0.52123127]
 [ 0.64676614 -0.50888826  1.          0.75765625  0.99989632]
 [ 0.98779789  0.1762633   0.75765625  1.          0.74817964]
 [ 0.63571655 -0.52123127  0.99989632  0.74817964  1.        ]]


## Compute cumulative sum & product

In [104]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.54286042 0.85891684 0.65215387]
 [0.77584032 1.63349704 0.78676737]
 [0.94140029 2.24617932 1.02555078]
 [1.64617884 2.59569785 1.30297474]
 [2.64509725 2.63631398 1.94879726]]


In [105]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.54286042 1.40177726 2.05393114]
 [0.2329799  1.0075601  1.1421736 ]
 [0.16555997 0.77824225 1.01702566]
 [0.70477855 1.05429707 1.33172103]
 [0.99891841 1.03953453 1.68535705]]


In [106]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[0.54286042 0.85891684 0.65215387]
 [0.12647557 0.66529998 0.08778871]
 [0.02093929 0.40761751 0.02096249]
 [0.01475756 0.14246987 0.0058155 ]
 [0.0147416  0.00578657 0.00375578]]


In [107]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[0.54286042 0.46627196 0.30408106]
 [0.2329799  0.18046162 0.02429257]
 [0.16555997 0.10143566 0.02422115]
 [0.70477855 0.24633316 0.06833872]
 [0.99891841 0.04057219 0.02620244]]


## Element-wise comparison

In [108]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [109]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


# Slicing & Indexing

In [85]:
import numpy as np
arr=np.array(range(1,13)).reshape(3,4)

## Row and Column indices
Select an element by row and column indices

In [86]:
print(arr)
print(arr[1][2])
# or more concisely
print(arr[2,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
11


## Indexing with slicing

In [23]:
print(arr)
print(arr[1:,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8]
 [10 11 12]]


In [35]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# print(arr)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## Assign a scalar to a slice by broadcasting

In [36]:
print("Original Array is \n",arr)
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print("Array is \n",arr)

Original Array is 
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Array is 
 [[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


## Boolean Indexing

In [60]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
list1=[True,False,True,False,True]
arr1[list1]
list2=np.array(['M','F',"M","M","F"])
print(arr1[list2=="M"])
print(arr1[arr1[:,4]>=10])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
# negate the condition
print(arr1[~(list2=="M")])
#print(arr1[~bools])    

[[ 5  6  7  8  9]
 [20 21 22 23 24]]


In [67]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2>=2) & (arr2<=4)])    

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Fancy indexing

In [71]:
arr = np.random.rand(10,5)
arr

array([[0.29085279, 0.60386373, 0.51757766, 0.38274572, 0.23561679],
       [0.92030664, 0.99755665, 0.44305418, 0.1376008 , 0.63436465],
       [0.56251265, 0.7241264 , 0.38099733, 0.75960706, 0.56415191],
       [0.08303586, 0.46149124, 0.04088332, 0.09110524, 0.19449452],
       [0.63314322, 0.97449027, 0.13481593, 0.31831246, 0.64765514],
       [0.26214364, 0.72698316, 0.36918414, 0.82796875, 0.31616781],
       [0.64698336, 0.31926835, 0.7306505 , 0.82414161, 0.45439775],
       [0.22560314, 0.56201887, 0.69070089, 0.48478335, 0.32761597],
       [0.02552627, 0.63812772, 0.31781858, 0.47987988, 0.15577584],
       [0.46050771, 0.71986776, 0.67118977, 0.73671073, 0.77029257]])

In [72]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.09110524 0.44305418 0.7241264 ]


In [74]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [4,2,3]])    

[[0.19449452 0.04088332 0.09110524]
 [0.63436465 0.44305418 0.1376008 ]
 [0.56415191 0.38099733 0.75960706]]


## Dimension inference

In [77]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(20)).reshape((4,-1))
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


## Find elements/indices by conditions

In [78]:
arr = np.arange(16).reshape(4,4)

In [79]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [124]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [125]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# Sort an Array

In [126]:
arr = np.random.rand(3,3)
arr

array([[0.85842765, 0.85244954, 0.95631203],
       [0.69794224, 0.80539694, 0.7331279 ],
       [0.60522684, 0.71735413, 0.71575041]])

## Sort an array along a specified axis

In [127]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.60522684 0.71735413 0.71575041]
 [0.69794224 0.80539694 0.7331279 ]
 [0.85842765 0.85244954 0.95631203]]


In [128]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.60522684 0.71735413 0.71575041]
 [0.69794224 0.80539694 0.7331279 ]
 [0.85842765 0.85244954 0.95631203]]


In [129]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.60522684 0.71575041 0.71735413]
 [0.69794224 0.7331279  0.80539694]
 [0.85244954 0.85842765 0.95631203]]


In [130]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.60522684 0.71575041 0.71735413]
 [0.69794224 0.7331279  0.80539694]
 [0.85244954 0.85842765 0.95631203]]


## Compute the indices that would sort an array along a specified axis

In [131]:
arr = np.random.rand(5,5)

In [132]:
# along the row
print(np.argsort(arr, axis=0))

[[0 4 2 2 1]
 [1 1 1 4 0]
 [4 0 4 0 3]
 [2 2 0 3 4]
 [3 3 3 1 2]]


In [133]:
# along the column
print(np.argsort(arr, axis=1))

[[0 3 4 1 2]
 [2 1 0 4 3]
 [2 3 1 0 4]
 [3 4 0 2 1]
 [3 1 2 0 4]]


In [134]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[12 13  0 23  7 21  3 22  6  5  9 20  4 18  1  8 11 19 10 24 14 15  2 17
 16]


In [135]:
arr = np.random.rand(3,4)

# Manipulate an Array

## transpose an array

In [80]:
# the following methods return a copy
arr=np.array(range(15)).reshape(3,5)
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## transpose of a high dimensional array with specified order of axes

In [81]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


## swap axes

In [138]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


## change the shape of an array

In [93]:
# change the shape of an array and return a copy
arr=np.array(range(12))
print(arr.reshape(2,6))
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [96]:
# change the shape of an array in place
arr.resize((2,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## flatten an array

In [105]:
x=arr.flatten() # return a copy
x[2]=100
print(x)
print(arr)

[  0   1 100   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [107]:
# change any element in the view will change the initial array
y=arr.ravel()   # return a view
y[2]=100
print(y)
print(arr)

[  0   1 100   3   4   5   6   7   8   9  10  11]
[[  0   1 100   3   4   5]
 [  6   7   8   9  10  11]]


## append elements to an array

In [109]:
arr = np.array([1,2,3])
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [110]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [116]:
L1=[1,2,3]
L2=[4,5,6]
L1.extend(L2)
print(L1)

[1, 2, 3, 4, 5, 6]


## Insert elements into an array

In [117]:
# np.insert(array, position, element)
# insert a scalar at a certain position
print(arr)
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[1 2 3]
[100   1   2   3]


In [118]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


## delete elements from an array

In [148]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [149]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


## Copy an array

In [150]:
arr = np.array([1,2,3])

In [121]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)
arr1[1]=20
print(arr)

[1 2 3]


# Combine & Split an Array

In [124]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [132]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [129]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [131]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [130]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [133]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [134]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Split an array 

In [135]:
arr = np.random.rand(4,4)

In [136]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.99202761, 0.05853121, 0.85328548, 0.08413249],
       [0.87778922, 0.44468216, 0.8542196 , 0.69537527]]), array([[0.84689964, 0.10274328, 0.02418669, 0.5780657 ],
       [0.95651321, 0.84379513, 0.20576018, 0.48634242]])]


In [137]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.99202761, 0.05853121],
       [0.87778922, 0.44468216],
       [0.84689964, 0.10274328],
       [0.95651321, 0.84379513]]), array([[0.85328548, 0.08413249],
       [0.8542196 , 0.69537527],
       [0.02418669, 0.5780657 ],
       [0.20576018, 0.48634242]])]


# Set Operations

### Select the unique elements from an array

In [7]:
arr = np.array([1,1,2,2,3,3,4,5,6])
r=np.unique(arr)
s=set(arr)     # Alternate Command
print(np.unique(arr))
print(set(arr))
print(r[0])    # subscriptable
# print(s[0]) TypeError: 'set' object is not subscriptable

[1 2 3 4 5 6]
{1, 2, 3, 4, 5, 6}
1


In [5]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
x, fx = np.unique(arr, return_counts=True)
print("X =",x)
print(x[0])
print("Fx=",fx)

X = [1 2 3 4 5 6]
1
Fx= [2 2 2 1 1 1]


### Intersection & Union of two arrays

In [10]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [11]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [166]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### Compute whether each element of an array is contained in another

In [20]:
print(np.in1d([1,6],[1,2,3,4,5]))

[ True False]


In [153]:
# preserve the shape of the array in the output, if the array is of higher dimensions
arr1=np.array(range(10)).reshape(2,5)
arr2=np.array(range(6,15))
print(np.isin(arr1, arr2))

[[False False False False False]
 [False  True  True  True  True]]


### Find the elements in an array that are not in another

In [23]:
print(np.setdiff1d([1,2,3,4],[1,2,5]))

[3 4]


## Find the elements in either of two arrays, but not both

In [24]:
print(np.setxor1d([1,2,3,4],[1,2,5]))

[3 4 5]


# Linear Algebra

In [26]:
arr1 = np.array(range(4)).reshape(2,2)
arr2 = np.array(range(5,9)).reshape(2,2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


### Matrix Multiplication

In [29]:
#print(arr1.dot(arr2))# or
#print(np.dot(arr1, arr2))# or
print(arr1 @ arr2)  # Matrix Multiplication in Matlab A*B
print(arr1 * arr2)  # Elementwise Multiplication in Matlab A.*B

[[ 7  8]
 [31 36]]
[[ 0  6]
 [14 24]]


### Cholesky Decompostion

In [33]:
mat=np.array([[4,12,-16],[12,37,-43],[-16,-43,98]])
print(np.linalg.cholesky(mat))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


### QR Factorization

In [35]:
#arr = np.random.rand(2,2)
q, r = np.linalg.qr(mat) # Factor the matrix arr as qr, where q is orthonormal and r is upper-triangular.
print("q:\n",q)
print("r:\n",r)
print("Matrix:\n",mat)
print("qr :\n",q.dot(r))

q:
 [[-0.19611614 -0.16947544  0.96582428]
 [-0.58834841 -0.76762404 -0.25416428]
 [ 0.78446454 -0.61808689  0.05083286]]
r:
 [[-20.39607805 -57.85425987 105.31436457]
 [  0.          -3.8580585  -24.85307452]
 [  0.           0.           0.45749571]]
Matrix:
 [[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
qr :
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


#### Singular Value Decomposition (SVD)

In [38]:
u, D, v = np.linalg.svd(mat)
print("u\n",u)
print("D\n",D)
print("v\n",v)

u
 [[-0.16300693 -0.21272739  0.96341881]
 [-0.45732393 -0.84895218 -0.26483016]
 [ 0.87423313 -0.48376363  0.04109976]]
D
 [1.23477232e+02 1.55039632e+01 1.88049805e-02]
v
 [[-0.16300693 -0.45732393  0.87423313]
 [-0.21272739 -0.84895218 -0.48376363]
 [ 0.96341881 -0.26483016  0.04109976]]


### Eigen values

In [39]:
print(np.linalg.eigvals(mat))

[1.23477232e+02 1.88049805e-02 1.55039632e+01]


#### Eigen value decomposition

In [40]:
print("Matrix:\n",mat)
eigen_values, eigen_vectors = np.linalg.eig(mat)
print("Eigen Values: ",eigen_values)    
print("Eigen Vectors:\n",eigen_vectors)

Matrix:
 [[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
Eigen Values:  [1.23477232e+02 1.88049805e-02 1.55039632e+01]
Eigen Vectors:
 [[ 0.16300693  0.96341881  0.21272739]
 [ 0.45732393 -0.26483016  0.84895218]
 [-0.87423313  0.04109976  0.48376363]]


#### Trace & Determinant

In [43]:
# notice this is not a function in linalg!!!
print(np.trace(mat))    

139


In [178]:
print(np.linalg.det(arr))

-0.2130400627389112


In [44]:
print(np.linalg.matrix_rank(mat))

3


In [46]:
print(np.linalg.cond(mat))
np.linalg.eigvals(mat)

6566.198356197774


array([1.23477232e+02, 1.88049805e-02, 1.55039632e+01])

#### Inverse/psedo-inverse of a matrix

In [47]:
mat=np.random.randint(0,10,(3,3))
print("Matrix:\n",mat)
print("Inverse of a matrix:\n",np.linalg.inv(mat))

Matrix:
 [[1 6 4]
 [1 3 9]
 [3 0 8]]
Inverse of a matrix:
 [[ 0.23529412 -0.47058824  0.41176471]
 [ 0.18627451 -0.03921569 -0.04901961]
 [-0.08823529  0.17647059 -0.02941176]]


In [191]:
print("Psudo-inverse of a matrix:\n",np.linalg.pinv(arr))

Psudo-inverse of a matrix:
 [[-0.21794872  0.11538462  0.3974359 ]
 [ 0.3974359  -0.26923077 -0.37179487]
 [ 0.11538462  0.11538462 -0.26923077]]


## Solve a Linear System

### Solve a linear system in closed form

In [197]:
print("Matrix:\n",arr)
y = [1,2,3]
print(np.linalg.solve(arr, y))

Matrix:
 [[9 6 5]
 [5 1 6]
 [6 3 1]]
[ 1.20512821 -1.25641026 -0.46153846]


In [199]:
# Calculate the least-squares solution of a linear system

In [200]:
y = [3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 1.79487179 -1.74358974 -0.53846154]
[]
3
[15.23541082  4.0337829   1.26919372]


<ipython-input-200-421cf372d30c>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)


In [ ]:
the various ways to add numbers in numpy array.

In [1]:
import numpy as np
arr1=np.array([[12, 41, 20], [1, 8, 5]])
print(arr1)
#### Appending Row-wise
print(np.append(arr1,[[41,80,14]],axis=0))
print('\n')
#### Appending column-wise
print(np.append(arr1,[[41,80,14],[71,15,60]],axis=1))
print('\n')

[[12 41 20]
 [ 1  8  5]]
[[12 41 20]
 [ 1  8  5]
 [41 80 14]]


[[12 41 20 41 80 14]
 [ 1  8  5 71 15 60]]




# <center> Thank You </center>