# NumPy

The NumPy library is the core library for scientific computing in Python. It provides a  high-performance multidimensional array object, and tools for working with these arrays.  

Use the following improt convention:  

In [1]:
import numpy as np

# Creating Arrays 

In [8]:
#import numpy as np
A1 = np.array([1,2,3])
A2 = np.array([(1,2,3),(4,5,6)], dtype = float)
A3 = np.array([[(1,2,3),(4,5,6)],[(3,2,1),(6,5,4)]], dtype = float)
A1, A2,A3

(array([1, 2, 3]),
 array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[[1., 2., 3.],
         [4., 5., 6.]],
 
        [[3., 2., 1.],
         [6., 5., 4.]]]))

# Initial Placeholders 

In [2]:
print(np.zeros((3,4))) # Create an array of zeros
print(np.ones((2,3,4))) # Create an array of ones

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
print(np.arange(10,25,5),) # Create an array of evenly spaced values (step value)
print(np.linspace(0,10,5))# Create an array of evenlyspaced values (number of samples)

[10 15 20]
[ 0.   2.5  5.   7.5 10. ]


In [5]:
print(np.full((3,3),7)) # Create a constant array
print(np.eye(3)) # Create a 2X2 identity matrix   

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print(np.random.random((2,2))) # Create an array with random values
print(np.empty((3,2))) # Create an empty array

[[0.35848997 0.80337367]
 [0.82457623 0.66551706]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


# I/O 
## Saving & Loading on Disk 

In [9]:
np.save('my_array', A2)
np.load('my_array.npy')

array([[1., 2., 3.],
       [4., 5., 6.]])

## Saving & Loading Text Files 

In [7]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter= ',')
np.savetxt( "myarray.txt", A2, delimiter= ",")

## Inspecting Your Array 

In [10]:
print(A1.shape) # Array dimensions
print(len(A1)) # Length of array
print(A2.ndim) # Number of array dimensions
print(A3.size) # Number of array elements

(3,)
3
2
12


# Array Mathematics 

## Arithmetic Operations 

In [12]:
A4=np.array([[0,1,0],[1,2,1]])
A4

array([[0, 1, 0],
       [1, 2, 1]])

In [13]:
A1

array([1, 2, 3])

In [14]:
print(A1 - A4) # Subtraction
print(np.subtract(A1,A4)) # Subtraction

print(A1+A4) # Addition 
print(np.add(A1,A4)) # Addition

print(A1/A4) # Division 
print(np.divide(A1,A4)) # Division 

print(A1*A4) # Multiplication 
print(np.multiply(A1,A4)) # Multiplication 

[[1 1 3]
 [0 0 2]]
[[1 1 3]
 [0 0 2]]
[[1 3 3]
 [2 4 4]]
[[1 3 3]
 [2 4 4]]
[[inf  2. inf]
 [ 1.  1.  3.]]
[[inf  2. inf]
 [ 1.  1.  3.]]
[[0 2 0]
 [1 4 3]]
[[0 2 0]
 [1 4 3]]


<ipython-input-14-76f374526454>:7: RuntimeWarning: divide by zero encountered in true_divide
  print(A1/A4) # Division
<ipython-input-14-76f374526454>:8: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(A1,A4)) # Division


In [15]:
print(np.exp(A1)) # Exponentiation

print(np.sqrt(A1)) # Square root

print(np.sin(A1)) # Print sines of an array

print(np.cos(A1)) # Elementwise cosine

print(np.log(A1)) # Elementwise natural logarithm

print(A2.dot(A1)) # Dot product 

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
[14. 32.]


In [18]:
A2.dot(A1)

array([14., 32.])

# Comparison 

In [ ]:
print(A1 == A4) # Elementwise comparison
print(A1< 2) # Elementwise comparison
print(np.array_equal(A1, A4)) # Arraywise comparison

# Copying Arrays 

In [44]:
#h = A2.view()# Create a view of the array with the same data
#np.copy(A2) # Create a copy of the array
print(A2)
h = np.copy(A2) # Create a deep copy of the array
#import copy
t=copy.deepcopy(A2)
A2[1][2]=8
print(A2)
print(h)
print(t)

[[1. 2. 3.]
 [4. 5. 9.]]
[[1. 2. 3.]
 [4. 5. 8.]]
[[1. 2. 3.]
 [4. 5. 9.]]
[[1. 2. 3.]
 [4. 5. 9.]]



# Sorting Arrays 

In [54]:
A1=np.array([[1,9,3],[6,7,2]])
#A1.sort() # Sort an array
A1.sort(axis=1) # Sort the elements of an array's axis
A1

array([[1, 3, 9],
       [2, 6, 7]])

# Subsetting, Slicing, Indexing 

## Subsetting

In [77]:
print(A1[1]) # Select the element at the 2nd index

print(A2[1,2]) # Select the element at row 1 column 2(equivalent to b[1][2])

[2 6 7]
8.0


## Slicing

In [ ]:
print(A3[0:2]) # Select items at index 0 and 1

print(A3[0:2,1]) # Select items at rows 0 and 1 in column 1

print(A4[:1])

In [ ]:
A1[ : : -1] # Reversed array A1 array([3, 2, 1])

## Boolean Indexing 

In [58]:
print(A2)
A2[A2<4] # Select elements from a less than 2
A2<4

[[1. 2. 3.]
 [4. 5. 8.]]


array([[ True,  True,  True],
       [False, False, False]])

# Array Manipulation 

## Transposing Array 

In [ ]:
print(A2)
i = np.transpose(A2) # Permute array dimensions
print(i.T) # Permute array dimensions

## Changing Array Shape 

In [60]:
print(A2)
print(A2.ravel()) # Flatten the array
print(A2.reshape(3, 2)) # Reshape, but don’t change data

[[1. 2. 3.]
 [4. 5. 8.]]
[1. 2. 3. 4. 5. 8.]
[[1. 2.]
 [3. 4.]
 [5. 8.]]


# Adding/Removing Elements 

In [ ]:
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

In [ ]:
A2.resize((1,6))
print(A2) # Return a new arraywith shape(2,6)
print(np.append(A2,[7,8,9])) # Append items to an array
print(np.insert(A2,1,5)) # Insert items in an array
print(np.delete(A2,[1])) # Delete items from an array

# Combining Arrays 

In [ ]:
A1=A1.reshape(-1,1)
A2=A2.reshape(2,3)
print(A2)
np.concatenate((A2,A2),axis=0) # Concatenate arrays
 
np.vstack((A2,2*A2)) # Stack arrays vertically(row wise)
 
np.r_[A2,2*A2] # Stack arrays vertically(row wise)

np.hstack((A2,2*A2)) # Stack arrays horizontally(column wise)
 
np.column_stack((A2,2*A2)) # Create stacked column wise arrays
 
np.c_[A2,2*A2] # Create stacked column wise arrays

In [67]:
#A1.ravel()
A1.reshape(-1,1)

array([[1],
       [3],
       [9],
       [2],
       [6],
       [7]])

# Splitting Arrays 

In [ ]:
print(A2)

print(np.hsplit(A2,3)) # Split the array horizontally at the 3rd index

print(np.vsplit(A2,2)) # Split the array vertically at the 2nd index

# Matrix Operations

In [68]:
M1= np.array([[1,2,4],[4,5,4],[7,8,9]])
M1

array([[1, 2, 4],
       [4, 5, 4],
       [7, 8, 9]])

In [69]:
M2=np.eye(3)
M2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
M1+M2
M1-M2
M1*M2

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [71]:
print(np.dot(M1,M2))
print(np.matmul(M1,M2))

[[1. 2. 4.]
 [4. 5. 4.]
 [7. 8. 9.]]
[[1. 2. 4.]
 [4. 5. 4.]
 [7. 8. 9.]]


In [73]:
print(M1)
print(np.linalg.det(M1))
print(np.linalg.matrix_rank(M1))
print(np.linalg.norm(M1))
print(np.linalg.matrix_power(M1, 2))
print(np.linalg.inv(M1))
print(np.trace(M1))

[[1 2 4]
 [4 5 4]
 [7 8 9]]
-15.0
3
16.492422502470642
[[ 37  44  48]
 [ 52  65  72]
 [102 126 141]]
[[-0.86666667 -0.93333333  0.8       ]
 [ 0.53333333  1.26666667 -0.8       ]
 [ 0.2        -0.4         0.2       ]]
15


In [74]:
print(np.linalg.eigvals(M1))

E,V=np.linalg.eig(M1)
print("Eigen Value:",E)
print("Eigen Vectors: \n",V)

[15.51769052 -1.27552592  0.7578354 ]
Eigen Value: [15.51769052 -1.27552592  0.7578354 ]
Eigen Vectors: 
 [[-0.29438368 -0.87789386  0.47600926]
 [-0.43548815  0.35408631 -0.79778462]
 [-0.85069872  0.3223744   0.37007416]]


Solve the system of equations $x_1 + 2 x_2 = 1$ and $3 x_1 + 5 x_2 = 2$:

In [75]:
A = np.array([[1, 2], [3, 5]])
B = np.array([1, 2])
np.linalg.solve(A, B)

array([-1.,  1.])