# Import Libraries

In [7]:
#import numpy   # numpy.fun()
import numpy as np # np.fun()
#from numpy import * # fun()

In [8]:
M= np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
m,n=M.shape
if m==n:
    print('Matrix is Square')
else:
    print('Matrix is not Square')

Matrix is Square


In [10]:
M3=np.array([[2,-2,-4],[-1,3,4],[1,-2,-3]])
M4=M3@M3
if (M4==M3).all():
    print('Matrix is idempotent.')
else:
    print('Matrix is not idempotent.')

Matrix is idempotent.


In [12]:
(M4==M3).all()

True

In [19]:
if (M3==M3.T).all():
    print('Matrix is Symmetric.')
else:
    print('Matrix is not Symmetric.')

Matrix is not Symmetric


In [13]:
M= np.array([[1,0,0],[0,0,-1],[0,-1,0]])
if np.linalg.det(M)!=0:
    if (np.linalg.inv(M)==M.T).all():
        print('Matrix is Orthogonal.')
else:
     print('Matrix is not Orthogonal.')

Matrix is Orthogonal.


In [36]:
Ev=np.linalg.eigvals(M)
if np.all(Ev>0):
    print('Positive Def')
elif np.all(Ev>=0):
    print('Positive Semi Def')
elif np.all(Ev<0):
    print('Negative Def')
elif np.all(Ev<=0):
    print('Negative Semi Def')
else:
    print('Indefinite')
    

In [ ]:
## Cramer's Rule

In [61]:
A=np.array([[2,-1,1],[1,1,-3],[5,-2,-4]])
B=np.array([-3,17,20])
row, col=A.shape
x=[0]*col
for i in range(col):
    temp=A.copy()
    temp[:,i]=B
    x[i]=np.linalg.det(temp)/np.linalg.det(A)
x

[2.0000000000000013, 2.9999999999999982, -3.999999999999999]

In [62]:
# G Inverse

In [61]:
M= np.array([[1,2,3],[4,5,6]])
#print(np.linalg.det(M))
print(np.linalg.matrix_rank(M))
print(np.linalg.matrix_rank(M[:,:2]))

G= np.zeros_like(M.T)*0.0
G[:2,:2]=(np.linalg.inv(M[:,:2]))
print(M)
print(M@G@M)

2
2
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [56]:
M[:,:2]

array([[1, 2],
       [4, 5]])

In [16]:
np.ix_([0,2],[0,2])

(array([[0],
        [2]]),
 array([[0, 2]]))

# Matrix and vector products

In [2]:
a = np.array([[1, 0], [0, 1]]) # np.eye(2)
b = np.array([[4, 1], 
              [2, 2]])
print(a)
print(b)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]


In [3]:
a*b

array([[4, 0],
       [0, 2]])

# Dot product of two arrays.

In [4]:

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [5]:
#Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.
A = np.random.random((2, 2))
B = np.random.random((2, 3))
C = np.random.random((3, 4))
D = np.random.random((4, 3))
# the actual dot multiplication
print(A)
print(B)
np.linalg.multi_dot([A, B, C, D])
# OR
# np.dot(np.dot(np.dot(A, B), C), D)
# OR
# A.dot(B).dot(C).dot(D)

[[0.52645136 0.87836401]
 [0.1421092  0.42550092]]
[[0.65355282 0.6391546  0.38547296]
 [0.95134629 0.7424884  0.47033677]]


array([[2.02518597, 1.29710828, 2.06431148],
       [0.84267352, 0.53832887, 0.85845221]])

In [6]:
# np.dot(B,A) # shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
#Return the dot product of two vectors.
a = np.array([[1,4],
              [4,2]])
b = np.array([[3, 2],
              [2,3]])
np.vdot(a, b)

25

In [8]:
1*3+4*2+4*2+2*3

25

In [12]:
a=np.array([1,2])
b=np.array([3,4])
np.vdot(a,b)

11

In [9]:
#Inner product of two arrays. Matrix Multiplication
print(a)
print(b)
np.inner(a, b)

[1 2]
[3 4]


11

In [11]:
#Compute the outer product of two vectors.
a=np.array([1,2])
b=np.array([[2,3],[5,2]])
print(a)
print(b)
np.outer(a, b)

[1 2]
[[2 3]
 [5 2]]


array([[ 2,  3,  5,  2],
       [ 4,  6, 10,  4]])

In [12]:
#Matrix product of two arrays.
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1, 2],
              [2, 2, 3]])
np.matmul(a, b)

array([[4, 1, 2],
       [2, 2, 3]])

In [13]:
# The @ operator can be used as a shorthand for np.matmul on ndarrays.
a@b

array([[4, 1, 2],
       [2, 2, 3]])

In [14]:
#Raise a square matrix to the (integer) power n.
a=np.array([[1,2],[3,4]])
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [15]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

In [16]:
a@a@a

array([[ 37,  54],
       [ 81, 118]])

In [17]:
#Kronecker product of two arrays.
print(a)
print(b)
np.kron(a, b)

[[1 2]
 [3 4]]
[[4 1 2]
 [2 2 3]]


array([[ 4,  1,  2,  8,  2,  4],
       [ 2,  2,  3,  4,  4,  6],
       [12,  3,  6, 16,  4,  8],
       [ 6,  6,  9,  8,  8, 12]])

In [18]:
#Decompositions

In [19]:
#Cholesky decomposition.
a=np.array([[6,15,55],
            [15,55,225],
            [55,225,979]])
np.linalg.cholesky(a)

array([[ 2.44948974,  0.        ,  0.        ],
       [ 6.12372436,  4.18330013,  0.        ],
       [22.45365598, 20.91650066,  6.11010093]])

In [20]:
np.linalg.matrix_rank(a)

3

In [21]:
#Compute the qr factorization of a matrix.
Q,R=np.linalg.qr(a)
print(Q)
print(R)

[[-0.10466885 -0.83044761 -0.54717566]
 [-0.26167214 -0.50781394  0.82076348]
 [-0.9594645   0.229089   -0.1641527 ]]
[[  -57.32364259  -231.84151249 -1003.94876177]
 [    0.            11.15854318    64.34537173]
 [    0.             0.            -6.12836734]]


In [22]:
np.linalg.norm(Q[0])

1.0

In [ ]:
#Singular Value Decomposition.
a=np.arange(9).reshape(3,3)+1
U,Sig,VT=np.linalg.svd(a)
print("Sig:",Sig)
U@np.diag(Sig)@VT

In [ ]:
#Matrix eigenvalues
#Compute the eigenvalues and right eigenvectors of a square array.
E,V=np.linalg.eig(a)
print("E=",E)
print("V=",V)

In [ ]:
#Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.
#np.linalg.eigh(a[, UPLO])

In [ ]:
#Compute the eigenvalues of a general matrix.
np.linalg.eigvals(a)

In [ ]:
#Compute the eigenvalues of a complex Hermitian or real symmetric matrix.
np.linalg.eigvalsh(a[, UPLO])

In [ ]:
#Norms and other numbers

In [ ]:
#Matrix or vector norm.
np.linalg.norm(x[, ord, axis, keepdims])

In [ ]:
#Compute the condition number of a matrix.
np.linalg.cond(x[, p])

In [ ]:
#Compute the determinant of an array.
np.linalg.det(a)

In [ ]:
#Return matrix rank of array using SVD method
np.linalg.matrix_rank(a)

In [ ]:
#Compute the sign and (natural) logarithm of the determinant of an array.
np.linalg.slogdet(a)

In [ ]:
#Return the sum along diagonals of the array.
np.trace(a)

In [ ]:
#Solving equations and inverting matrices

In [ ]:
#Solve a linear matrix equation, or system of linear scalar equations.
linalg.solve(a, b)

In [ ]:
#Solve the tensor equation a x = b for x.
linalg.tensorsolve(a, b[, axes])

In [ ]:
#Return the least-squares solution to a linear matrix equation.
linalg.lstsq(a, b[, rcond])

In [ ]:
#Compute the (multiplicative) inverse of a matrix.
linalg.inv(a)

In [ ]:
#Compute the (Moore-Penrose) pseudo-inverse of a matrix.
linalg.pinv(a[, rcond, hermitian])

In [ ]:
#Compute the ‘inverse’ of an N-dimensional array.
linalg.tensorinv(a[, ind])

In [ ]:
#Compute tensor dot product along specified axes.
tensordot(a, b[, axes])

In [ ]:
#Evaluates the Einstein summation convention on the operands.
einsum(subscripts, *operands[, out, dtype, …])

In [ ]:
#Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.
einsum_path(subscripts, *operands[, optimize])