# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the dataset

In [3]:
dataset=pd.read_csv("data/Social_Network_Ads.csv")
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
dataset=dataset.drop(['User ID','Gender'],axis=1)

In [11]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [12]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

## Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
x_train.head()

Age  EstimatedSalary
253   37           146000
58    22            18000
378   41            87000
56    23            48000
143   30            89000

## Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.0467767 ,  2.26737932],
       [-1.46904122, -1.54384265],
       [ 0.33249384,  0.51064419],
       [-1.37422359, -0.6505875 ],
       [-0.71050014,  0.57019454],
       [ 1.09103492,  0.54041937],
       [-0.71050014, -0.62081233],
       [-1.08977068, -0.53148681],
       [ 0.2376762 ,  0.24266765],
       [-0.99495305, -1.15676542],
       [-1.75349413,  0.45109385],
       [ 0.99621728,  0.59996971],
       [ 1.37548782,  0.59996971],
       [-0.23641197, -0.76968819],
       [ 0.33249384,  0.03424145],
       [ 1.65994073,  1.64210072],
       [ 0.14285857,  1.91007726],
       [ 1.849576  , -1.30564128],
       [ 0.42731147,  0.59996971],
       [ 0.2376762 ,  1.10614763],
       [-1.46904122, -0.4421613 ],
       [-0.61568251, -1.63316816],
       [-1.27940595, -1.2758661 ],
       [ 0.2376762 , -0.38261096],
       [-0.0467767 , -0.50171164],
       [-1.18458832, -1.42474196],
       [-1.65867649,  0.48086902],
       [-0.80531778,  0.15334213],
       [ 1.09103492,

## Training the Logistic Regression model on the Training set

In [16]:
from sklearn.linear_model import LogisticRegression
LRclassifier=LogisticRegression()

LRclassifier.fit(x_train,y_train)

LogisticRegression()

## Predicting a new result

In [24]:
print(LRclassifier.predict(scaler.transform([[0,0]])))

[0]


## Predicting the Test set results

In [25]:
y_pred=LRclassifier.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int64)

In [26]:
y_test

207    0
354    1
369    1
336    1
273    1
      ..
10     0
298    0
111    0
371    1
93     0
Name: Purchased, Length: 100, dtype: int64

## Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test,y_pred)

array([[55,  9],
       [18, 18]], dtype=int64)

In [28]:
accuracy_score(y_test,y_pred)

0.73